micronaut:
  application:
    name: micronautOpenapiExample
  router:
    static-resources:
      rapidoc:
        paths: 'classpath:META-INF/swagger/views/rapidoc'
        mapping: '/**'
netty:
  default:
    allocator:
      max-order: 3

openapi:
  spec-file: 'classpath:META-INF/swagger/openapi.json'
security:
  oauth:
    client-id: 'client-id'
    client-secret: 'client-secret'
    authorization-endpoint: 'authorization-endpoint'
    token-endpoint: 'token-endpoint'
